language: python

python:
  - 3.7
  - 3.8

branches:
  only:
    - master

os:
  - linux

dist: bionic

install:
  - pip3 install --upgrade pip
  - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
  - pip3 install flake8 pytest
script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 . --count --exit-zero --ignore=E722,E731,F401 --max-line-length=127 --statistics
  - pytest
